name: Secrets Management Lab

on:
  push:
    branches: [main]

jobs:
  reveal-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show masked secret
        run: echo "The secret is ${{ secrets.MY_SECRET_MESSAGE }}"

      - name: Write secret to temp file
        run: |
          echo "${{ secrets.MY_SECRET_MESSAGE }}" > secret.txt
          echo "Secret saved to secret.txt"
